name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      GOPATH: C:\gopath
      GOARCH: 386
      GOOS: windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up environment
      run: |
        echo %GOPATH%
        echo %GOARCH%
        echo %GOOS%
        set PATH=%GOPATH%\bin;C:\go\bin;%PATH%
        go version
        go env

    - name: Run Tests
      run: go test -v ./...

    - name: Build Project
      run: go build

    - name: Create Archive
      run: |
        7z a god_of_war_browser.zip -r c:\gopath\src\github.com\mogaika\god_of_war_browser\web -x!*.go
        7z a god_of_war_browser.zip god_of_war_browser.exe
        7z a god_of_war_browser.zip font_aliases.cfg
        7z a god_of_war_browser.zip font_aliases.ru.cp1251.cfg
        7z a god_of_war_browser.zip LOCALIZATION.md
        7z a god_of_war_browser.zip README.md
        7z a god_of_war_browser.zip hashes.dump.txt
        7z a god_of_war_browser.zip strings.dump.txt
        mv god_of_war_browser.zip god_of_war_browser.${{ github.run_number }}.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: archive
        path: god_of_war_browser.${{ github.run_number }}.zip

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.run_number }}
        name: god_of_war_browser.${{ github.run_number }}
        body: Automatic release ${{ github.run_number }}
        files: god_of_war_browser.${{ github.run_number }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify Success on Discord
      if: success()
      run: |
        Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -OutFile send.ps1
        .\send.ps1 success ${{ secrets.WEBHOOK_URL }}

    - name: Notify Failure on Discord
      if: failure()
      run: |
        Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -OutFile send.ps1
        .\send.ps1 failure ${{ secrets.WEBHOOK_URL }}
